### ISSUE TITLE
Automatic Disconnect on Youtube

### ISSUE THREAD

**Issue by Catarax** [serv-inc/safe-search#26]
When I login to youtube, the panel on the right side is automatically opened and clicked to disconnect me.
I have to disable the extension to keep logged in.

Chromium Version 76.0.3809.100

**Comment by serv-inc** [comment]
This is by design, as YouTube only offers two levels of content filtering. To choose the third, least-restrictive level, the only way I have found so far is to log you out. See also https://github.com/serv-inc/safe-search/wiki/Configure. 

Would a notification if this happens help?

**Comment by Catarax** [comment]
A notification would be much better, thank you!

**Comment by andrewjong** [comment]
Is there a way to completely disable YouTube restrictions, then (like a -1 option)? I only care about safe search on search engines, since YouTube already does a good job at filtering racy content.

**Comment by serv-inc** [comment]
@andrewjong : pull requests welcome. Maybe set as -1.

**Comment by amzaf** [comment]
This has never been an issue with the extension on Firefox even in the "Under 18" mode. Please fix this issue on Chrome. I have to disable restrictions on Youtube because comments in languages based on the Arabic alphabet are erroneously flagged as restricted on Youtube. When the extension logs me out each time I visit Youtube, I'm effectively logged out of all Google service like gmail,...

**Comment by serv-inc** [comment]
see #39
